config/routes.rb
Invoices::Application.routes.draw do
  mount_opro_oauth
  devise_for :users

  root to: 'invoices#index'

  namespace :api do
    namespace :v1 do
      resources :clients do
        resources :invoices
      end
    end
  end

  resources :clients
  resources :invoices

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, :email, :user_id, presence: true

  has_many :invoices
  belongs_to :user
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :user
  belongs_to :client

  validates :amount, :status, :due_date, :client, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clients
  has_many :invoices, through: :clients
end

app/controllers/api/v1/clients_controller.rb
module Api
  module V1
    class ClientsController < ApplicationController
      skip_before_filter :verify_authenticity_token
      before_filter :authenticate_user!
      respond_to :json
      allow_oauth!

      def index
        @clients = current_user.clients.order(:company_name)
        respond_with @clients, status: :ok
      end

      def show
        @client = current_client
        respond_with @client, status: :ok
      end

      def create
        @client = current_user.clients.build(client_params)
        @client.save
        respond_with @client, status: :created
      end

      def update
        @client = current_client
        @client.update_attributes(client_params)
        respond_with @client, status: :ok
      end

      def destroy
        @client = current_client
        @client.destroy
        respond_with @client, status: :ok
      end

      private

      def current_client
        current_user.clients.where(params[:id]).first
      end

      def client_params
        params.require(:client).permit(:name, :email, :company_name)
      end
    end
  end
end

app/controllers/api/v1/invoices_controller.rb
module Api
  module V1
    class InvoicesController < ApplicationController
      skip_before_filter :verify_authenticity_token
      before_filter :authenticate_user!
      respond_to :json
      allow_oauth!

      def index
        @invoices = client.invoices
        respond_with @invoices, status: :ok
      end

      def show
        @invoice = client.invoices.where(params[:id]).first
        respond_with @invoice, status: :ok
      end

      def create
        @invoice = client.invoices.build(invoice_params)
        @invoice.save
        respond_with @invoice, status: :created, location: api_v1_client_invoices_url(@invoice)
      end

      def update
        @invoice = client.invoices.where(params[:id]).first
        @invoice.update_attributes(invoice_params)
        respond_with @invoice, status: :ok
      end

      def destroy
        @invoice = client.invoices.where(params[:id]).first
        @invoice.destroy
        respond_with @invoice, status: :ok
      end

      private

      def client
        @client ||= current_user.clients.where(id: params[:client_id]).first
      end

      def invoice_params
        params.require(:invoice).permit(:due_date, :amount, :status)
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @clients = current_user.clients
  end

  def edit
    @client = current_user.clients.find(params[:id])
  end

  def update
    @client = current_user.clients.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to clients_path, notice: 'Client updated successfully'
    else
      render :edit
    end
  end

  def create
    @client = current_user.clients.build(client_params)
    if @client.save
      redirect_to clients_path
    else
      render :new
    end
  end

  def new
    @client = current_user.clients.build
  end
  
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:company_name, :name, :email)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @invoices = current_user.invoices 
  end

  def new
    @clients = current_user.clients
    @invoice = Invoice.new
  end

  def create
    @invoice = current_user.invoices.build(invoice_params)
    if @invoice.save
      redirect_to invoices_path, notice: "Invoice created"
    else
      render :new
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:due_date, :amount, :status, :client_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Client</h1>
    <p><%= link_to "Back to Clients", clients_path %></p>

    <%= form_for @client, role: "form" do |f| %>
      <% if @client.errors.any? %>
        <div class="error_explanation">
          <div class="alert alert-danger">The form contains <%= pluralize @client.errors.count, "error" %>.</div>
          <ul>
            <% @client.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :company_name, "Company Name" %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.text_field :company_name, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :name %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <div class="row">
          <div class="col-sm-6">
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/clients/edit.html.erb
<%= render 'form' %>

app/views/clients/index.html.erb
<h1>Clients <small>Home</small></h1>

<p><%= link_to "New Client", new_client_path %></p>

<table id="clients" class="table table-striped">
    <tr>
      <th>Company</th>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.company_name %></td>
      <td><%= client.name %></td>
      <td><%= client.email %></td>
      <td>
        <%= link_to edit_client_path(client), id: "#{client.id}-edit", class: "btn btn-primary btn-sm" do %>
          <span class="glyphicon glyphicon-edit"></span> 
        <% end %>

        <%= link_to client_path(client), id: "#{client.id}-delete", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" do %>
          <span class="glyphicon glyphicon-remove"></span> 
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/clients/new.html.erb
<%= render "form" %>

app/views/invoices/index.html.erb
<h1>Invoices <small>Home</small></h1>

<p><%= link_to "New Invoice", new_invoice_path %></p>

<table id="invoices" class="table table-striped">
    <tr>
      <th>Invoice ID</th>
      <th>Due Date</th>
      <th>Amount</th>
      <th>Status</th>
    </tr>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.unique_id %></td>
        <td><%= invoice.due_date.strftime("%d %b %Y") %></td>
        <td><%= number_to_currency(invoice.amount) %></td>
        <td><%= invoice.status %></td>
      </tr>
    <% end %>
</table>

app/views/invoices/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Invoice <small>New</small></h1>
    <p><%= link_to "Back to Invoices", invoices_path %></p>

    <%= form_for @invoice, role: "form" do |f| %>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Invoices</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Invoices", root_path, class: "navbar-brand" %>  
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Clients", clients_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, data: { method: :delete } %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render "layouts/messages" %> 
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </div>
</body>
</html>